<a href="https://colab.research.google.com/github/keshorerode/Machine_Learning_colab/blob/main/ex2_Data_Manipulation_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
arr = np.array([11, 12, 13, 14, 15])
y = arr.copy()

arr[0] = 42
print(arr)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42 12 13 14 15]
[11 12 13 14 15]


In [3]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
print(np.split(arr,2))

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [4]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print(np.where(arr==2))

[0 1 2 3]
(array([1]),)


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
x=arr.reshape(2,3)
print( x)

[[1 2 3]
 [4 5 6]]
